module: traffic-accounting-nginx-module
nginx_branches:
  - mainline
  - stable
variants:
  - name: combined
    configure_flags: --with-stream
  - name: http-only
    configure_flags: ""
  - name: stream-only
    configure_flags: --without-http --with-stream
last_build:
  version: v20260601-snapshot
  commit: daf570a4a00c7cdffe043973ca0056acf89067e0
  date: "2026-06-01T23:13:14Z"
  nginx_versions:
    stable: 1.30.2
    mainline: 1.31.1
